# --- Jekyll Config --- 

title: "😼 Lucy Radio - 24/7 🤖"
url: "https://lrmn.is-a.dev/Lucy-Radio/"
remote_theme: "dracula/gh-pages"

# --- Misc ---

# Output options (more information on Jekyll's site)
timezone: "Asia/Jakarta"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# --- Plugins ---

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
#  - jekyll-paginate
#  - jekyll-sitemap
